#!/bin/sh
#
# Starts sampler driver.
#
NAME=sampler
PID_FILE="/var/run/sampler.pid"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
	printf "Starting sampler: "

    echo 60010000.dma-controller > /sys/bus/platform/drivers/uio_pdrv_genirq/unbind
    echo 60000000.sampler > /sys/bus/platform/drivers/uio_pdrv_genirq/unbind
    modprobe dma-sampler

	echo "OK"
}
stop() {
	printf "Stopping sampler: "

    modprobe -r dma-sampler
    echo 60010000.dma-controller > /sys/bus/platform/drivers/uio_pdrv_genirq/bind
    echo 60000000.sampler > /sys/bus/platform/drivers/uio_pdrv_genirq/bind

	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

