#!/usr/bin/env bash

HOST_DIR="$(dirname $(realpath $0))/buildroot/output/host"

FRONTEND_DIR="${HOST_DIR}/ui/react-frontend-webgl2"
VENV_DIR="${HOST_DIR}/ui/venv"

case "$1" in
    "frontend")
        if [ ! -d ${FRONTEND_DIR}/node_modules ]; then
            echo "$0: no node modules found"
            echo "Try running 'make' in the buildroot directory."
            exit 1
        fi

        ${HOST_DIR}/bin/npm --prefix ${FRONTEND_DIR} run dev
        ;;

    "server")
        if [ ! -d ${VENV_DIR} ]; then
            echo "$0: no python virtual environment found"
            echo "Try running 'make' in the buildroot directory."
            exit 1
        fi

        source ${VENV_DIR}/bin/activate
        export LD_LIBRARY_PATH=${HOST_DIR}/lib:${LD_LIBRARY_PATH}

        cd ${HOST_DIR}/ui
        python3 ${HOST_DIR}/ui/adc_server.py
        ;;

    *)
        echo "Usage: $0 TARGET"
        echo ""
        echo "TARGET must be either 'frontend' or 'server'."
        exit 1
        ;;
esac
