#!/bin/sh
#
# Starts adc_server.py
#
NAME=adc_server
PID_FILE="/var/run/$NAME.pid"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
    printf "Starting adc_server: "
    start-stop-daemon -S -qbm -p $PID_FILE -x /usr/bin/python3 -- /ui/adc_server.py
    echo "OK"
}
stop() {
    printf "Stopping adc_server: "
    start-stop-daemon -K -q -p $PID_FILE
    echo "OK"
}
restart() {
    stop
    start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
